POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="zWBSmqHyIOKG4f8UeaEm65p89GnQPIw-.jpg"

< J:\Java\Image\zWBSmqHyIOKG4f8UeaEm65p89GnQPIw-.jpg


### get image
GET http://localhost:8080/api/v1/attach/open/Screenshot.png

### get image by id
GET http://localhost:8080/api/v1/attach/open/ac202ae9-e728-4f76-a053-afa54ec50616/img

### get general by id
GET http://localhost:8080/api/v1/attach/open/7c7768d5-f0c4-420c-b19d-3a91d2c370e3/general

### get pagination
GET http://localhost:8080/api/v1/attach/admin/pagination?page=1&size=30
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAzMTc3OTAsImlkIjoyLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjkwNDA0MTkwLCJpc3MiOiJrdW51eiB0ZXN0IHBvcnRhbGkifQ.fpAxGi1sTZK-EXWlTPALlS3TMgbV5OILgeoj9KTiX_uy9UPJWbK7PHnuZaz3VTSwYRuFqhn5rOI5wgbeQ6ZRHw


### delete by id
DELETE http://localhost:8080/api/v1/attach/admin/delete/1e6fc1d4-128e-4b8c-967d-4a9b2e395a2b.mp4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAxOTcyMTUsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2OTAyODM2MTUsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.Cbn3Fv8I2QNQ5Fy98SVlTEUFVQuOQAj6x4n0nK48mv42cztSrhjhyQ1w9zAhu38MKub9KJhUw5hOmbEX2a7rgQ

