### login ADMIN
POST localhost:8080/api/v1/auth/login
Content-Type:  application/json

{
  "phone": "+998996742127",
  "password": "Java_1java"
}

### login PUBLISHER
POST localhost:8080/api/v1/auth/login
Content-Type:  application/json

{
  "phone": "+998901112233",
  "password": "Aziz1"
}

### login MODERATOR
POST localhost:8080/api/v1/auth/login
Content-Type:  application/json

{
"phone": "+998991113344",
"password": "Farrux1"
}

### login MODERATOR
POST localhost:8080/api/v1/auth/registration
Content-Type:  application/json

{
  "name": "Javohir",
  "surname": "Mengliboyev",
  "phone": "+998996742127",
  "email": "javohscript@gmail.com",
  "password": "kunkun"
}

### Email verification
GET localhost:8080/api/v1/auth/verification/email/dasdasdasd