### 1. Create
POST localhost:8080/api/v1/category/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg

{
  "orderNumber": 8,
  "nameUz": "Audio",
  "nameRu": "Аудио",
  "nameEng": "Audio"
}

### 2. Update
PUT localhost:8080/api/v1/category/update_order_by_id?id=4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg

{
  "orderNumber": 4
}

### 3. Delete by id
DELETE localhost:8080/api/v1/category/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg

### 4. Get All
GET localhost:8080/api/v1/category
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg

### 4. Get By Language
GET localhost:8080/api/v1/category/by_lang?lang=en
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg
