### 1. Create
POST localhost:8080/api/v1/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg

{
  "name": "Dfdgv",
  "surname": "Fvdvdbv",
  "email": "vadscdl22@gmail.com",
  "phone": "+998901110039",
  "password": "orifvaliP8",
  "status": "ACTIVE",
  "role": "USER"
}

### 2. Update
PUT localhost:8080/api/v1/profile/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjMyNTAsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjY4NTAsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.KpGFKfiKfthREsv2JgGDY1zmmfwsYsUu9LeddTHcx16HuOxu7iCCJwBtOyXZiolerpn6-pTGiTj0Nya4nJJY_Q


{
  "role": "USER",
  "visible": 1
}

### 2. Update for User
PUT localhost:8080/api/v1/profile/for_user/4
Content-Type: application/json

{
  "name": "Valli"
}

### 4. Get All
GET localhost:8080/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg


### 5. Delete by id
DELETE localhost:8080/api/v1/profile/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg


### 7. Filter
POST localhost:8080/api/v1/profile/filter?page=1&size=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg


{
  "name": "Ali"
}