### 1. Create
POST localhost:8080/api/v1/region
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg

{
  "orderNumber": 14,
  "nameUz": "Sirdaryo",
  "nameRu": "Сырдарья",
  "nameEng": "Syr Darya"
}

### 2. Update
PUT localhost:8080/api/v1/region/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg

{
  "orderNumber": 4
}

### 3. Delete by id
DELETE localhost:8080/api/v1/region/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg

### 4. Get All
GET localhost:8080/api/v1/region
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg

### 4. Get By Language
GET localhost:8080/api/v1/region/by_lang?lang=ru
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg
