### 1. Create
POST localhost:8080/api/v1/tag
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAzNTExOTYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2OTA0Mzc1OTYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.fEA269xmvmL-c4A9mSm4KbJAd_B28eh6PyxPsWIfatkONCD3IuiBYQfiQb9CQ8aUSoPzsLdECrhbMf0EFqzftA

{
  "orderNumber": 1,
  "name": ""
}

### 2. Update
PUT localhost:8080/api/v1/tag/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg

{
  "orderNumber": 6
}

### 3. Delete by id
DELETE localhost:8080/api/v1/tag/5
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg

### 4. Get All
GET localhost:8080/api/v1/tag
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NjIzODYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjU5ODYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.TRBFzQgB9ukl9CTXtu9JBqFllcPMXSojMc2sHLSCehYlKyGX60h8M0PFqOTt5VdZFRNvTRE5Lqv9lgluTroKFg

